logging:
  level:
    ROOT: info
    "[org.hibernate.SQL]": DEBUG
    "[tee.spotify_clone_back]": DEBUG

spring:
  profiles:
    active: dev
  application:
    name: spotify-clone
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    hikari:
      poolName: Hikari
      auto-commit: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        "[default_schema]": spotify_clone
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/master.xml
    default-schema: spotify_clone
    enabled: true
  #    drop-first: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: ${AUTH0_CLIENT_ID}
            client-secret: ${AUTH0_CLIENT_SECRET}
            scope: openid, profile, email
            # redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          okta:
            issuer-uri: https://dev-l7dg8uux7qwsjeod.us.auth0.com/
      resourceserver:
        jwt:
          issuer-uri: https://dev-l7dg8uux7qwsjeod.us.auth0.com/
server:
  port: 8080
